### ISSUE TITLE
Script element layout should be aware of junctions

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1271]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1271)
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Mar 25, 2020, 11:59

## Summary

This does not work, but it should:

```
kind: script

build-depends:
- junction.bst:foo.bst
- foo.bst

config:
  layout:
  - element: junction.bst:foo.bst
    destination: / 
  - element: foo.bst
    destination: /sysroot
```

## What is the current bug behavior?

[//]: # (What actually happens)

```
script element at a.bst [line 1 column 0]: script element at a.bst [line 1 column 0]: 'junction.bst:foo.bst' in layout not found in dependencies
```

## What is the expected correct behavior?

[//]: # (What you should see instead)

It should correctly build.

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----
