### ISSUE TITLE
Should we allow filtering tar source content?

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1302]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1302)
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 6, 2020, 20:21

## Summary

[//]: # (Summarize the bug encountered concisely)

Sometimes, tarfiles have `node` type files (dev and such), and extracting them with BuildStream will therefore be impossible as a normal unprivileged user.

The user however might not want to have those files extracted and could filter them out.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

A simple `import` of a stage3 from gentoo:

```
kind: import

sources:
- kind: tar
  url: https://gentoo.osuosl.org//releases/amd64/autobuilds/current-stage3-amd64-nomultilib/hardened/stage3-amd64-hardened+nomultilib-20200422T214502Z.tar.xz
  ref: 9b390b887949488e771d17b3fedd04edcc1071061b2338ec2fffb01242aef669
```

## What is the current bug behavior?

[//]: # (What actually happens)

Trying to build this as an unprivileged user will error out with the unhelpful:

```
        [00:14:21] FAILURE stages/0.bst: tar source at stages/0.bst [line 4 column 2]: Error staging source: [Errno 1] Operation not permitted
```

## What is the expected correct behavior?

[//]: # (What you should see instead)

1) We give a more helpful explanation to the user
2) We allow filtering tar files?
