### ISSUE TITLE
Needless requirement for ports in Execution service definition

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1332]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1332)
In GitLab by [[Gitlab user @pointswaves]](https://gitlab.com/pointswaves) on May 31, 2020, 23:18

## Summary

```
    cat > ~/.config/buildstream.conf << EOF 
    remote-execution:
      execution-service:
        url: https://remotebuild.pointswaves.co.uk:443
        client-key: $CLIENT_KEY
        client-cert: $CLIENT_CERT
      storage-service:
        url: https://cache.pointswaves.co.uk:443
        client-key: $CLIENT_KEY
        client-cert: $CLIENT_CERT
      action-cache-service:
        url: https://cache.pointswaves.co.uk:443
        client-key: $CLIENT_KEY
        client-cert: $CLIENT_CERT
    EOF 

```

Missing off the `:443` Causes:

```
[00:00:11][9f42840b][   build:freedesktop-sdk.bst:bootstrap/build/debugedit-build.bst] FAILURE You must supply a protocol and port number in the action-cache-service url, for example: http://buildservice:50051.
```

This seems very odd when
```
    cat > ~/.config/buildstream.conf << EOF 
    artifacts:
    - url: https://cache.pointswaves.co.uk
      client-key: $CLIENT_KEY
      client-cert: $CLIENT_CERT
      push: true
    EOF 

```
works fine

Please see https://gitlab.com/pointswaves/embbeded-selfy/-/jobs/574850671 for more details
