### ISSUE TITLE
Buildstream should provide a `buildsystem` repo with common buildsystems

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1354]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1354)
In GitLab by [[Gitlab user @tcanabrava]](https://gitlab.com/tcanabrava) on Jul 8, 2020, 11:30

When creating a small project for a flatpak or snap, what we need is to get the sources of our application, configure a small script for buildstream that tells bst: `this target depend on the following list of platforms, and use this buildtool` but currently we need to specify inside of the `kind: cmake` that we have cmake:

```
kind: cmake
description: dolphin

depends:
- filename: bootstrap-import.bst
  junction: freedesktop-sdk.bst
- filename: public-stacks/buildsystem-cmake.bst
  junction: freedesktop-sdk.bst
```

Even tough I'm talking about cmake here, this extends to meson and other buildsystems.
