### ISSUE TITLE
Buildstream should provide plugins for language-package-managers

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1355]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1355)
In GitLab by [[Gitlab user @tcanabrava]](https://gitlab.com/tcanabrava) on Jul 8, 2020, 11:36

I want to be able to write this in my buildstream scripts:

```
kind: irrelevant
description: my-test-app

depends:
- filename: ruby
  junction: core
- filename: python
  junction: core
- ruby-gem: rails
  version: 1.5
- python3-pip: pygame
  version: 3.0
```

that will greatly simplify configuration of smaller projects. I assume we need to implement a version this for the most used projects (php, ruby, python, npm, rust, conan, vcpkg) to simplify usage.
