### ISSUE TITLE
Buildstream should refuse to build if disk space is too low.

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1402]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1402)
In GitLab by [[Gitlab user @tcanabrava]](https://gitlab.com/tcanabrava) on Oct 5, 2020, 13:41

Because of an unrelated bug in buildstream I was locked out of my linux box: the cache filled up ~/ completely and not even login was possible. I do have a fairly sized drive but the cache was bigger, so we should warn the user (someway, somehow) that he does not have the required amount of space after build for the cached artifacts.

We already have a feature to store the sha256 of the files, I propose a extension of that.
```
element:
  ref: (sha256 here)
  download-size: - (automatically filled for the specific sha256)
  artifact-size: - (automatically filled for the specific sha265)
```

of course this is impossible to have for the first build, but if we are using things as a external junction, this junction will have those element numbers, and buildstream can sum the necessary disk space for usage, and warn if the current size is too low before attempting a build.
