### ISSUE TITLE
Impossible to remove workspace for module that no longer exists

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#249]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/249)
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on Feb 12, 2018, 23:49

I have the following workspaces open:

```
[mcatanzaro[[Gitlab user @victory-road]](https://gitlab.com/victory-road) gnome-build-meta]$ bst workspace list
workspaces:
- element: apps/libgnome-games-support.bst
  directory: /home/mcatanzaro/Projects/libgnome-games-support
- element: core-deps/glib.bst
  directory: /home/mcatanzaro/Projects/glib
- element: core/epiphany.bst
  directory: /home/mcatanzaro/Projects/epiphany
- element: core/glib-networking.bst
  directory: /home/mcatanzaro/Projects/glib-networking
```

I want to remove the workspace for `core/glib-networking.bst` because I deleted that element, replacing it with `core-deps/glib-networking.bst`. But it's not possible:

```
$ bst workspace close core/glib-networking.bst
[--:--:--] START   Loading pipeline
[00:00:00] FAILURE Loading pipeline
Error loading pipeline: Could not find file at /home/mcatanzaro/Projects/gnome-build-meta/elements/core/glib-networking.bst
```

To close the workspace, it seems I first have to revert the commit that removed the element, then close the workspace, then undo the revert. It would be nice if that was not required.
