### ISSUE TITLE
Make dependency type default to build

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#463]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/463)
In GitLab by [[Gitlab user @sstriker]](https://gitlab.com/sstriker) on Jul 8, 2018, 18:09

## Background

.bst files are verbose for the common case of dependencies.

I am seeing .bst files that look like
```
depends:
- filename: a.bst
  type: build
- filename: b.bst
  type: build
...
- filename: z.bst
  type: build
```

## Task description

Make the dependency type default to `build`, to reduce verbosity
