### ISSUE TITLE
bst --track modifies bst files even when their source refs are unchanged

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#470]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/470)
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Jul 11, 2018, 12:27

## Summary

After discussion, it has been identified that:
* ruamel.yaml is imperfect, when we rewrite a file, some indentation will be changed and whitespace will change in some places
  * it's still not horrible, comments and order is properly preserved, and whitespace is preserved in most cases, but it could be better
* After introducing the `project.refs` feature (in commits referred to in the discussion below), it seems that we are rewriting the element `.bst` files at `bst track` time even when the ref has not changed.

## Steps to reproduce

- `bst --track` an element with custom indentation 
- git diff the file, and see indentation changes

## What is the current bug behavior?

When running bst-track, indentation, ordering and comments are not preserved.

## What is the expected correct behavior?

bst track should update the version/sha, but respect the files formatting.

## Relevant logs and/or screenshots

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/318/diffs

## Example element

``` YAML
kind: manual
description: Build curl
# Comment comment pls remember
depends:
- base.bst
# ruamel isn't quite working
sources:
- kind: git
  url: https://github.com/curl/curl.git

config:
  build-commands:
  - ./buildconf
  - ./configure
  - make
```

After bst track <file>:
``` YAML
config:
  build-commands:
  - ./buildconf
  - ./configure
  - make
depends:
- base.bst
description: Build curl
kind: manual
sources:
- kind: git
  ref:
  url: https://github.com/curl/curl.git
```

## Possible fixes

review changes in 19cad981 as this is where the regression appears to have been caused.

## BuildStream version affected:

bst version: 1.1.3+4.g0916d81e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jul 24, 2018, 12:57

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Jul 30, 2018, 09:41

assigned to [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Jul 30, 2018, 15:35

This issue appears to be a regression caused by 19cad981.

Specifically, the change to source.py as detailed [here](https://gitlab.com/BuildStream/buildstream/commit/19cad981007d514cf15218b783ae05ed16cb511a#note_91250406).

[[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) mentions in the commit message `This also fixes _set_ref() to apply the ref to the node unconditionally, this must be done independantly of whether the ref actually changed.`

## To reproduce

- Take a standard bst project.
- Modify a `.bst` files indentation to be 4 spaces.
- `bst track <file.bst>` or `bst build --track <file.bst> <file.bst>`
- Observe indentation change within the file.

## Information required

* [ ]  Why do we write to the .bst files (What changes are we potentially making to the nodes)
* [ ]  Why must we write regardless of whether or not anything changed?

## Further investigation

I'm looking further into this, however ruamel appears to struggle with certain formatting.

### Using ruamel.yaml

Before round trip load
```
value: test
nextline: |

  This is some text on another line.

# Comment comment
ls:
-   a: alpha
    b: bravo

# Did you say dictionary??
Ages:

    John:
    - 23

    Paul:
    - 42
```

After round trip dump
``` YAML
value: test
nextline: |2

  This is some text on another line.

# Comment comment
ls:
- a: alpha
  b: bravo

# Did you say dictionary??
Ages:

  John:
  - '23'

  Paul:
  - '42'
```

## _yaml.py

As for the _yaml.py module within BuildStream, I am currently unable to:

`_yaml.dump(_yaml.load("file.yaml"))`

Without RepresenterError being raised by ruamel. (I may have missed some internals to how _yaml.py works)
