### ISSUE TITLE
Add `all` value to depends `type`

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#61]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/61)
In GitLab by [[Gitlab user @sstriker]](https://gitlab.com/sstriker) on Aug 4, 2017, 16:44

When you specify a dependency the default is to have it be available in both `build` and `run`.  There is no way to explicitly state `all`, you need to leave `type` undefined.  We propose the ability to use the syntax below so one can be explicit.

```yaml
kind: manual

depends:
- filename: b.bst
  type: all
```
