### ISSUE TITLE
Conditionals not supported in element overrides

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#658]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/658)
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Sep 17, 2018, 21:34

## Summary

Trying to use a conditional inside an element override, I get an error: Value of '(?)' is not of the expected type 'str'

## Steps to reproduce

Here is a small project.conf to reproduce

```
name: testcase

options:
  arch:
    type: arch
    description: architecture
    values: [i686, x86_64]

elements:
  autotools:
    variables:
      (?):
      - arch == 'i686':
          conf-global: --host=i686-unknown-linux-gnu
      - arch == 'x86_64':
          conf-global: --host=x86_64-unknown-linux-gnu
```

## What is the current bug behavior?

```
project.conf [line 13 column 6]: Value of '(?)' is not of the expected type 'str'
```

## What is the expected correct behavior?

It should work

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.2

----
