### ISSUE TITLE
Better error messages for `bst track` for cross-junction elements

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#960]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/960)
In GitLab by [[Gitlab user @chiaratolentino]](https://gitlab.com/chiaratolentino) on Mar 13, 2019, 18:35

## Summary

[//]: # (Summarize the bug encountered concisely)
Error messages for `bst track` when junctions are involved do not contain enough information.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)
`junctions/junction-a.bst`
```yaml
kind: junction
sources:
- kind: git
  track: master
  url: upstream:foo/junction-a
  ref: someref12345
```

`org/repo-a.bst`
```yaml
kind: import
depends:
- junctions/junction-a.bst:root-junction-a.bst
sources:
- kind: git
  track: master
  url: upstream:org/repo-a
```

`Contents of foo/junction-a repository`
```bash
root-junction-a.bst
```

## What is the current bug behavior?

[//]: # (What actually happens)
Since the `foo/junction-a` project does not have a `project.conf` file, we get the following output when trying to run `bst source track org/repo-a.bst`:
```bash
[--:--:--][        ][ main:core activity                 ] START   Track
[--:--:--][        ][ main:core activity                 ] START   Loading elements
[00:00:00][        ][ main:core activity                 ] FAILURE Loading elements
[00:00:00][        ][ main:core activity                 ] FAILURE Track

Could not find element 'root-junction-a.bst' in elements directory 'elements'
```
which does not tell us much about the actual problem

## What is the expected correct behavior?

[//]: # (What you should see instead)

Ideally, the error message should say something along the lines of 
```bash
Junction 'junction-a.bst' does not point to a valid BuildStream project
```

----
